package com.syuuk.patentflow.patent.dto;

public enum ReviewWorkflowStatus {
    NOT_IN_REVIEW_QUARTER,
    REVIEW_QUARTER_STARTED,
    REPORT_GENERATED,
    MAIL_READY,
    WAITING_BUSINESS_RESPONSE,
    BUSINESS_RESPONSE_RECEIVED,
    WAITING_EXECUTIVE_APPROVAL,
    APPROVAL_COMPLETED,
    LEGAL_ACTION_RECORDED
}
