apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patentflow-be
  namespace: patentflow
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.patentflow.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patentflow-be
                port:
                  number: 80
