apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team11-patentflow-be-ingress
  namespace: patentflow
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: team11-patentflow-be
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    - host: api.patentflow.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: team11-patentflow-be-svc
                port:
                  number: 80
