apiVersion: v1
kind: Secret
metadata:
  name: 11-team-patentflow-postgres-secret
  namespace: patentflow
type: Opaque
stringData:
  POSTGRES_DB: "patentflow"
  POSTGRES_USER: "patentflow"
  POSTGRES_PASSWORD: "patentflow"
