apiVersion: v1
kind: Secret
metadata:
  name: team11-patentflow-be-secret
  namespace: patentflow
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "replace-me"
  PATENTFLOW_JWT_SECRET: "replace-with-at-least-32-byte-secret"
  PATENTFLOW_BOOTSTRAP_ADMIN_USERNAME: "admin@example.com"
  PATENTFLOW_BOOTSTRAP_ADMIN_PASSWORD: "replace-me"
  PATENTFLOW_BOOTSTRAP_ADMIN_DISPLAY_NAME: "특허관리자"
  PATENTFLOW_BOOTSTRAP_BUSINESS_USERNAME: "business@example.com"
  PATENTFLOW_BOOTSTRAP_BUSINESS_PASSWORD: "replace-me"
  PATENTFLOW_BOOTSTRAP_BUSINESS_DEPARTMENT_ID: "DEPT-ICT"
  PATENTFLOW_BOOTSTRAP_BUSINESS_DISPLAY_NAME: "사업부 데모 담당자"
  GMAIL_USERNAME: ""
  GMAIL_APP_PASSWORD: ""
  PATENTFLOW_KIPRIS_SERVICE_KEY: ""
