apiVersion: v1
kind: Service
metadata:
  name: patentflow-be
  namespace: patentflow
spec:
  type: ClusterIP
  selector:
    app: patentflow-be
  ports:
    - name: http
      port: 80
      targetPort: http
